### ISSUE TITLE
Skip Template Columns

### ISSUE THREAD

**Issue by qjhart** [ucd-library/trello2moment#10]
The current trello2moment has some columns that need to be skipped.  Right now, the plan is only to skip the column with the name *Card Creation Guides*, otherwise all cards are added.  Is this the best plan for card inclusion

**Comment by wrenaria** [comment]
Yes, I think that is fine. Perhaps we should rename the column "Card Creation Guides / Not Exported" and that way in the future if there are cards that end up being pulled out of the content (this happened with Chardonnay with content that fell beyond our chosen time frame) they can be put in that column and we know they won't be exported but the content research will also not be lost in case we want to use it in a future subject. 

I assume you also do not pull in "archived" cards? That's another way we can handle hiding extra content without total deletion.

**Comment by qjhart** [comment]
@wrenaria Actually, see #11.  I hadn't been doing that, but need to start.  Also, we can just ignore any card that is template and we are probably good without worrying about the column name.

**Comment by wrenaria** [comment]
It would be better to ignore the column itself because the instructions for using the templates are written in normal cards, not as templates (it wouldn't make sense to make them templates).
