### ISSUE TITLE
Trello - Add Rule to Documentation

### ISSUE THREAD

**Issue by ldragoon** [ucd-library/trello2moment#12]
If a user goes to the Google Maps page for a location and there is only a g.page short link available in the Share popup (eg: https://g.page/stagsleapwine?share) avoid using it, as we can't parse them properly, and enter the full address (eg: https://www.google.com/maps/place/Stag's+Leap+Wine+Cellars/@38.3992276,-122.3257286,17z/data=!3m1!4b1!4m8!1m2!3m1!2sStag's+Leap+Wine+Cellars!3m4!1s0x80850024581748e9:0x799218271937af8c!8m2!3d38.3992275!4d-122.3235402)

**Comment by wrenaria** [comment]
Updated the instructions for templates on Trello. The offending links have been fixed on the JOP board. Moving forward, we will just use the full url Google instead of shortened "share" url to avoid this happening again.
