### ISSUE TITLE
Proper URL decoding

### ISSUE THREAD

**Issue by qjhart** [ucd-library/trello2moment#13]
The Google Maps interface properly URL encodes the location names.  These need to be properly decoded in order to work.   
decoding goes [here](https://github.com/ucd-library/trello2moment/blob/cf42265818c6a14b4a78b5b2dd49bbd48e87af93/trello2moment#L173)

**Comment by qjhart** [comment]
Looking at https://github.com/ucd-library/trello2moment/blob/abe9e4e90659cb7a651ef3b83c21c801eb996416/trello2moment#L175 

Should this be decodeURIComponent?

**Comment by ldragoon** [comment]
I'm happy to switch it - I read the docs for both and couldn't decide which option was better.

**Comment by qjhart** [comment]
Make sure to close the issue on submission.

**Comment by ldragoon** [comment]
Will do!
