### ISSUE TITLE
Need the TTL file describing the moment

### ISSUE THREAD

**Issue by qjhart** [ucd-library/trello2moment#15]
There are two json files, that should be created, the moment itself (nearly done), but we should also create the TTL description file for adding the moment to the DAMS.  This uses the board description as inputs.  For this we probably need to think about the command line parameters and how to standardize where things are saved.

**Comment by ldragoon** [comment]
Required items for moment description TTL file:
  1. Description (desc)
  2. Background Image for Thumbnail
    (prefs > backgroundImageScaled)
      Acknowledgment - photo
  3. Board Title (name)
  4. Subject Terms
  5. Licensing
