### ISSUE TITLE
Example Trello Board for testing

### ISSUE THREAD

**Issue by qjhart** [ucd-library/trello2moment#17]
Now that we have a good standard, we need to make sure that we have a good trello test board that we can freely mess around with.  My suggestion is that we copy Kimmy's to a new board, 'trello2moment'  and make a smaller example that we can freely test.  

We need to check with Kimmy on that, to make sure we understand everything, we don't want to do any damage by mistake.

Create a new `example` branch for this.

**Comment by ldragoon** [comment]
I created the new "example" branch.

**Comment by wrenaria** [comment]
Here's a copy of my board for testing: https://trello.com/invite/b/pY20Yz5x/ed66c6ae9d9ef122aff94c7f6798c48f/trello2moment

Do with it what you will.
