### ISSUE TITLE
Write the ${moment}.ttl file

### ISSUE THREAD

**Issue by qjhart** [ucd-library/trello2moment#36]
The `trello2moment` will now create a *moment* directory.  In this directory, there will be all the images that are used for the moment.  There will also be a *${moment}_moment.ttl* file that gets created.  The Makefile converts this to a json file at ${moment}/moment.json.  

However, we are still not creating the definition of the moment itself.  This should automatically be created as well. 

For example running 
` ./trello2moment --verbose --thumbnails --key=$key token=$tok --board=pY20Yz5x --moment=cats` should create 
`cats_moment.ttl` - The moment, to be converted to json w/ RIOT
`cats.ttl` - The description of the moment
`cats` - The directory holding all the images, and the moment.json file.

The `cats.ttl` file needs the descriptive information of the moment itself.  Not the individual cards.  This is also in the trello2moment download.

**Comment by ldragoon** [comment]
Created branch moment-definition for this issue.
