### ISSUE TITLE
#About vs #Keywords

### ISSUE THREAD

**Issue by ldragoon** [ucd-library/trello2moment#42]
Keywords => Just text
About => MUST have URLs (and perhaps labels)

For both of these, list items are treated as one item, so eg. if you have a keyword that looks like 

``` markdown
# Keywords
- foo; bar
```
That would be a single word of "foo; bar"  as opposed to 

``` markdown
# Keywords
- foo
- bar
```

There are 3 link types we need to be able to parse in the about section;

Normal Markdown

``` markdown
- [Title](url)
``` 

Or the URL space then label.  That is everything in the list after the URL is the label.

``` markdown
#about 
-http://wiki.org/cats Cats Are People too
```
would have a label *Cats are People too*

compare the about and keywords predicates:
https://schema.org/CreativeWork 

The image below shows three examples of links: 

![image](https://user-images.githubusercontent.com/7807437/83669153-f2258500-a585-11ea-8fe7-90687523a724.png)

**Comment by qjhart** [comment]
@ldragoon, I want to make it clear, you won't really be able to save the label anyways, that can't be sotred in the moments.ttl file.  But we can save it in yet another ttl file.
