### ISSUE TITLE
Standardize URL representation for creators and relatedLinks

### ISSUE THREAD

**Issue by qjhart** [ucd-library/trello2moment#57]
The URL representation issue as in: So creator on cabernet is coming in as a string:

```json
"creator" : "https://www.heitzcellar.com/purchase-2/marthas-vineyard-cabernet-sauvignon-oakville-napa-valley/",
```
and sometimes 

``` json
"creator" : [ "UC Davis Library", {
      "@id" : "https://www.library.ucdavis.edu/"
    } ]
```
is due to the fact that `riot` tries to guess the allowed values for the predicates, and sometimes guesses, wrong.  In the first case, it thinks creators will always be links, in the second requires that links be explicitly defined.  

I think maybe the most simple solution would be to fix the creator, and associate the text and the label.  So, we could do what we did with relatedLinks, `{name:"",url:""}`

**Comment by jrmerz** [comment]
I'm ok with this.  Let me know when ready will take a app code change
