### ISSUE TITLE
Inconsistancy with a few Trello Location Cards

### ISSUE THREAD

**Issue by ldragoon** [ucd-library/trello2moment#9]
**QUESTION**

So far each item that comes in via the jop.json generated by Trello should have an associated location object, such as:

[0]: {
@id: "_:b0",
@type: "schema:Place",
latitude: 0,
longitude: 0,
name: "Something place",
url: "google maps link"
}

Currently London is listed as: 

["London, United Kingdom", "51.50735, -0.12775"]

There is no link to an associated _:bX item.  Is this desired behavior or a mistake?

**Related Item**

Another location  is similarly not associated w/a _:bX item and looks like this:

["Location name to display (Ex: Livermore, California)", "Google Maps link"]

**Comment by qjhart** [comment]
Waiting on #5 I have created a stop gap -measure to test the JOP moment.  Basically, a quick search and replace for the existing locations.   The attached file includes all the google maps files, and their associated metadata.  @ldragoon can also use this as a test for the code for #5.

[location.txt](https://github.com/ucd-library/trello2moment/files/4093197/location.txt)
